apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-frontend
  namespace: pos
  labels:
    app: pos-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pos-frontend
  template:
    metadata:
      labels:
        app: pos-frontend
    spec:
      containers:
        - name: pos-frontend
          image: headie1/pos-frontend:0.0.1
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: pos-frontend-service
  namespace: pos
spec:
  selector:
    app: pos-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
