apiVersion: v1
kind: ConfigMap
metadata:
  name: pos-frontend-config
  namespace: pos
data:
  REACT_APP_API_URL: "http://pos-backend-service:5000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-frontend
  namespace: pos
  labels:
    app: pos-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pos-frontend
  template:
    metadata:
      labels:
        app: pos-frontend
    spec:
      containers:
        - name: pos-frontend
          image: headie1/pos-frontend:0.0.3
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: pos-frontend-config
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: pos-frontend-service
  namespace: pos
spec:
  selector:
    app: pos-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer